apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: my-flask-app
  type: NodePort #Type of the Kubernetes Service nodeport changed to Nodeport
  ports:
  - protocol: TCP
    port: 5000 #Service port test
    targetPort: 5000 #The port for the application container
